apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-app
          image: joyboy123/argocd:ccfa73f5a5589d5e7e944f614c9a630e4bf04cd7
          ports:
            - containerPort: 3000