apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-app
          image: joyboy123/argocd:5921ff1efe6a5e543cd4ca82f77a0e905a4f8ed8
          ports:
            - containerPort: 3000