apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-app
          image: joyboy123/argocd:7f15ff7b9333c1341e7205e1d74c491faa306b78
          ports:
            - containerPort: 3000