apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ include "gitops-cicd-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "gitops-cicd-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
