namespace: qa
replicaCount: 2

image:
  repository: joyboy123/argocd
  tag: "ea6c49f8039efc72c9c9fd81eae90a66bbe6f0f1"
  pullPolicy: IfNotPresent

nameOverride: "argocd-app"
fullnameOverride: "argocd-app"

service:
  name: "argocd-service"
  type: ClusterIP
  port: 80
  targetPort: 3000
