namespace: qa
replicaCount: 2

image:
  repository: joyboy123/argocd
  tag: "ca877164916e7e69c9e09a0b815bfe9a340d625e"
  pullPolicy: IfNotPresent

nameOverride: "argocd-app"
fullnameOverride: "argocd-app"

service:
  name: "argocd-service"
  type: ClusterIP
  port: 80
  targetPort: 3000
